# Generated by Django 4.2.2 on 2023-06-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0002_rename_reference_payment_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ref',
            new_name='reference',
        ),
    ]
